// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnboardingTask.Models;

namespace OnboardingTask.Migrations
{
    [DbContext(typeof(masterContext))]
    partial class masterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnboardingTask.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("OnboardingTask.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("OnboardingTask.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Customerid");

                    b.Property<DateTime>("DateSold")
                        .HasColumnType("datetime");

                    b.Property<int>("Productid");

                    b.Property<int>("Storeid");

                    b.HasKey("Id");

                    b.HasIndex("Customerid");

                    b.HasIndex("Productid");

                    b.HasIndex("Storeid");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("OnboardingTask.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("OnboardingTask.Models.Sales", b =>
                {
                    b.HasOne("OnboardingTask.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("Customerid")
                        .HasConstraintName("FK_customerId");

                    b.HasOne("OnboardingTask.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("Productid")
                        .HasConstraintName("FK_productId");

                    b.HasOne("OnboardingTask.Models.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("Storeid")
                        .HasConstraintName("FK_storeId");
                });
#pragma warning restore 612, 618
        }
    }
}
